language: java
services:
  - docker
cache:
  directories:
jdk:
  - oraclejdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean test jacoco:report coveralls:report
after_script:
  - docker build -t chsldz/tenniskoenig .
  - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
  - docker push chsldz/tenniskoenig
