language: java
services:
  - docker
cache:
  directories:
jdk:
  - oraclejdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean test jacoco:report coveralls:report
    - $HOME/.m2
after_script:
  - docker build -t chsldz/tenniskoenig .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push chsldz/tenniskoenig
