INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (1, 'Erwachsener ', 'Spieler', 0, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (2, 'Sven', 'Haala', 0, 1, 'sven.haala', '821f498d827d4edad2ed0960408a98edceb661d9f34287ceda2962417881231a');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (3, 'Tobias', 'Fritz', 0, 0, 'tobias.fritz', '821f498d827d4edad2ed0960408a98edceb661d9f34287ceda2962417881231a');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (4, 'Marvin', 'Kubik', 0, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (20, 'Tom', 'Riddle', 0, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (21, 'Max', 'Riese', 0, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (22, 'Tina', 'Müller', 1, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (23, 'Peter ', 'Pan', 0, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (24, 'Hans', 'Meier', 0, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (26, 'Thomas', 'Mozart', 1, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (27, 'Ben', 'Schmitt', 0, 0, '', '');
INSERT INTO TenniskoenigDB.user (id, vorname, nachname, geschlechtw, admin, username, password) VALUES (28, 'Jonas ', 'Seydel', 0, 0, '', '');